name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build binary
    - run: docker run -v `pwd`:/code -ti nixos/nix:latest nix-shell -p gnumake --run "cd /code/src/ && make"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: src/srv/MiSTer_WebMenu
