name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build binary
      run: docker run -v `pwd`:/code -t nixos/nix:latest nix-shell -p gnumake --run "nix-channel --remove nixpkgs && nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs && nix-channel --update && cd /code/src/ && make"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: webmenu.sh
        path: src/webmenu.sh
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: src/webmenu.sh
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
