name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build binary
      run: docker run -v `pwd`:/code -t nixos/nix:latest nix-shell -p gnumake --run "cd /code/src/ && make"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MiSTer_WebMenu
        path: src/srv/MiSTer_WebMenu
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: src/srv/MiSTer_WebMenu
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
